CREATE TABLE IF NOT EXISTS document(
  documentId INT NOT NULL AUTO_INCREMENT
  ,title VARCHAR(255) DEFAULT NULL
  ,body VARCHAR(255) DEFAULT NULL
  , created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
  , updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
  , PRIMARY KEY(documentId)
);